packages:
  - packages/*
  - examples/*

overrides:
  graphql: 16.13.1
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@<10.2.1: ">=10.2.1"
  minimatch@>=10.0.0 <10.2.3: ">=10.2.3"
  undici@>=7.0.0 <7.18.2: ">=7.18.2"
  wrangler@>=4.0.0 <4.59.1: ">=4.59.1"
