/**
 * AI AGENTS DO NOT EDIT THIS FILE
 *
 * UNLESS SPECIFICALLY ASKED BY THE HUMAN
 */

/**
 * Data-driven regression test harness.
 *
 * Runs every scenario against both the runtime interpreter and the AOT
 * compiler, with built-in log/trace capture and parse→serialise→parse
 * round-trip validation.
 *
 * @module
 */

import assert from "node:assert/strict";
import test, { afterEach, before, describe } from "node:test";
import {
  parseBridgeFormat as parseBridge,
  serializeBridge,
  type BridgeDocument,
} from "../../src/index.ts";
import { bridgeTransform } from "@stackables/bridge-graphql";
import { executeBridge as executeRuntime } from "@stackables/bridge-core";
import {
  executeBridge as executeCompiled,
  type ExecuteBridgeOptions,
} from "@stackables/bridge-compiler";
import type { ToolTrace } from "@stackables/bridge-core";
import {
  buildTraversalManifest,
  decodeExecutionTrace,
  SELF_MODULE,
} from "@stackables/bridge-core";
import {
  GraphQLList,
  GraphQLNonNull,
  buildSchema as buildGraphQLSchema,
  execute as executeGraphQL,
  getNamedType,
  isObjectType,
  parse as parseGraphQL,
  print as printGraphQL,
  visit,
  type GraphQLOutputType,
  type GraphQLSchema,
} from "graphql";
import type { Bridge } from "@stackables/bridge-core";
import { omitLoc } from "./parse-test-utils.ts";
import { GraphQLSchemaObserver } from "./observed-schema/index.ts";

// ── Round-trip normalisation ────────────────────────────────────────────────

/** Strip locations and sort wire arrays so order differences don't fail. */
function normalizeDoc(doc: unknown): unknown {
  const stripped = omitLoc(doc) as any;
  for (const instr of stripped?.instructions ?? []) {
    if (Array.isArray(instr.wires)) {
      instr.wires.sort((a: any, b: any) =>
        JSON.stringify(a) < JSON.stringify(b) ? -1 : 1,
      );
    }
  }
  return stripped;
}

// ── Log capture ─────────────────────────────────────────────────────────────

export type LogEntry = {
  level: "debug" | "info" | "warn" | "error";
  args: any[];
};

function createCapturingLogger() {
  const logs: LogEntry[] = [];
  return {
    logs,
    logger: {
      debug: (...args: any[]) => logs.push({ level: "debug", args }),
      info: (...args: any[]) => logs.push({ level: "info", args }),
      warn: (...args: any[]) => logs.push({ level: "warn", args }),
      error: (...args: any[]) => logs.push({ level: "error", args }),
    },
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object") {
    return false;
  }

  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

interface SelectionTree {
  [key: string]: SelectionTree;
}

function buildSelectionTreeFromPaths(paths: string[]): SelectionTree {
  const root: SelectionTree = {};

  for (const path of paths) {
    let ref = root;
    for (const segment of path.split(".").filter(Boolean)) {
      ref[segment] ??= {};
      ref = ref[segment];
    }
  }

  return root;
}

function orderSelectionTree(
  tree: SelectionTree | null,
  preferredOrder?: string[],
): SelectionTree | null {
  if (!tree || !preferredOrder || preferredOrder.length === 0) {
    return tree;
  }

  const ordered: SelectionTree = {};
  const seen = new Set<string>();

  for (const fieldName of preferredOrder) {
    if (tree[fieldName] !== undefined) {
      ordered[fieldName] = tree[fieldName]!;
      seen.add(fieldName);
    }
  }

  for (const [fieldName, child] of Object.entries(tree)) {
    if (!seen.has(fieldName)) {
      ordered[fieldName] = child;
    }
  }

  return ordered;
}

function unwrapOutputType(type: GraphQLOutputType): GraphQLOutputType {
  let current = type;
  while (current instanceof GraphQLNonNull) {
    current = current.ofType;
  }
  return current;
}

function buildSelectionTreeFromType(
  type: GraphQLOutputType,
  seen = new Set<string>(),
): SelectionTree | null {
  const unwrapped = unwrapOutputType(type);
  if (unwrapped instanceof GraphQLList) {
    return buildSelectionTreeFromType(unwrapped.ofType, seen);
  }

  const named = getNamedType(unwrapped);
  if (!isObjectType(named) || seen.has(named.name)) {
    return null;
  }

  const nextSeen = new Set(seen);
  nextSeen.add(named.name);

  const tree: SelectionTree = {};
  for (const [fieldName, fieldDef] of Object.entries(named.getFields())) {
    tree[fieldName] = buildSelectionTreeFromType(fieldDef.type, nextSeen) ?? {};
  }

  return tree;
}

function buildSelectionTreeForValue(
  value: unknown,
  type: GraphQLOutputType,
  seen = new Set<string>(),
): SelectionTree | null {
  const unwrapped = unwrapOutputType(type);

  if (unwrapped instanceof GraphQLList) {
    const firstDefined = Array.isArray(value)
      ? value.find((item) => item !== null && item !== undefined)
      : undefined;
    return firstDefined === undefined
      ? buildSelectionTreeFromType(unwrapped.ofType, seen)
      : buildSelectionTreeForValue(firstDefined, unwrapped.ofType, seen);
  }

  const named = getNamedType(unwrapped);
  if (!isObjectType(named) || seen.has(named.name)) {
    return null;
  }

  if (!isPlainObject(value)) {
    return buildSelectionTreeFromType(unwrapped, seen);
  }

  const nextSeen = new Set(seen);
  nextSeen.add(named.name);

  const tree: SelectionTree = {};
  for (const key of Object.keys(value).sort()) {
    const fieldDef = named.getFields()[key];
    if (!fieldDef) {
      continue;
    }
    tree[key] =
      buildSelectionTreeForValue(
        (value as Record<string, unknown>)[key],
        fieldDef.type,
        nextSeen,
      ) ?? {};
  }

  return tree;
}

function renderSelectionTree(tree: SelectionTree | null): string {
  if (!tree || Object.keys(tree).length === 0) {
    return "";
  }

  const body = Object.entries(tree)
    .map(([fieldName, child]) => {
      const renderedChild = renderSelectionTree(child);
      return renderedChild.length > 0
        ? `${fieldName} ${renderedChild}`
        : fieldName;
    })
    .join(" ");

  return `{ ${body} }`;
}

function ensureExecutableSDL(typeDefs: string): string {
  return typeDefs.includes("type Query {")
    ? typeDefs
    : `type Query {\n  _: Boolean\n}\n\n${typeDefs}`;
}

function ensureExecutableSDLForOperation(
  typeDefs: string,
  operation: string,
): string {
  const [rootTypeName] = operation.split(".");

  if (rootTypeName === "Mutation") {
    return typeDefs.includes("type Query {")
      ? typeDefs
      : `type Query {\n  _: Boolean\n}\n\n${typeDefs}`;
  }

  if (rootTypeName === "Query") {
    return ensureExecutableSDL(typeDefs);
  }

  return `schema {\n  query: ${rootTypeName}\n}\n\n${typeDefs}`;
}

function relaxInputNullabilityInSDL(typeDefs: string): string {
  const ast = parseGraphQL(typeDefs);
  const relaxedAst = visit(ast, {
    InputValueDefinition(node) {
      if (node.type.kind === "NonNullType") {
        return {
          ...node,
          type: node.type.type,
        };
      }

      return undefined;
    },
    FieldDefinition(node) {
      if (node.type.kind === "NonNullType") {
        return {
          ...node,
          type: node.type.type,
        };
      }

      return undefined;
    },
  });

  return printGraphQL(relaxedAst);
}

function normalizeGraphQLValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => normalizeGraphQLValue(item));
  }

  if (isPlainObject(value)) {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entryValue]) => [key, normalizeGraphQLValue(entryValue)]),
    );
  }

  return value;
}

function cloneObservationValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => cloneObservationValue(item));
  }

  if (isPlainObject(value)) {
    return Object.fromEntries(
      Object.entries(value).map(([key, entryValue]) => [
        key,
        cloneObservationValue(entryValue),
      ]),
    );
  }

  return value;
}

function setObservationPath(
  target: Record<string, unknown>,
  path: string[],
  value: unknown,
): void {
  let cursor = target;

  for (const segment of path.slice(0, -1)) {
    const current = cursor[segment];
    if (!isPlainObject(current)) {
      cursor[segment] = {};
    }
    cursor = cursor[segment] as Record<string, unknown>;
  }

  const leaf = path[path.length - 1];
  if (leaf !== undefined) {
    cursor[leaf] = cloneObservationValue(value);
  }
}

function getObservationPath(value: unknown, path: string[]): unknown {
  let current = value;

  for (const segment of path) {
    if (!isPlainObject(current)) {
      return undefined;
    }
    current = current[segment];
  }

  return current;
}

function mergeObservedSelection(
  exemplar: Record<string, unknown>,
  value: unknown,
  selectedPaths?: string[],
): Record<string, unknown> {
  const merged = cloneObservationValue(exemplar) as Record<string, unknown>;

  if (!selectedPaths || selectedPaths.length === 0) {
    if (isPlainObject(value)) {
      for (const [key, entryValue] of Object.entries(value)) {
        merged[key] = cloneObservationValue(entryValue);
      }
    }
    return merged;
  }

  for (const selectedPath of selectedPaths) {
    const path = selectedPath.split(".").filter(Boolean);
    const selectedValue = getObservationPath(value, path);
    if (selectedValue !== undefined) {
      setObservationPath(merged, path, selectedValue);
    }
  }

  return merged;
}

function observationSampleForPlan(
  exemplar: Record<string, unknown>,
  value: unknown,
  selectedPaths?: string[],
): unknown {
  if (!selectedPaths || selectedPaths.length === 0) {
    return value;
  }

  return mergeObservedSelection(exemplar, value, selectedPaths);
}

function getOperationField(schema: GraphQLSchema, operation: string) {
  const [rootTypeName, fieldName] = operation.split(".") as [
    "Query" | "Mutation",
    string,
  ];
  const rootType =
    rootTypeName === "Mutation"
      ? schema.getMutationType()
      : schema.getQueryType();

  assert.ok(rootType, `GraphQL root type ${rootTypeName} not found`);
  const field = rootType.getFields()[fieldName];
  assert.ok(field, `GraphQL field ${operation} not found in inferred schema`);

  return { rootTypeName, fieldName, field };
}

function buildGraphQLOperationSource(
  schema: GraphQLSchema,
  operation: string,
  expectedData: unknown,
  requestedFields?: string[],
  preferredFieldOrder?: string[],
): string {
  const { rootTypeName, fieldName, field } = getOperationField(
    schema,
    operation,
  );
  const variableDefinitions = field.args.length
    ? `(${field.args.map((arg) => `$${arg.name}: ${arg.type.toString()}`).join(", ")})`
    : "";
  const args = field.args.length
    ? `(${field.args.map((arg) => `${arg.name}: $${arg.name}`).join(", ")})`
    : "";

  const selectionTree = orderSelectionTree(
    requestedFields?.length
      ? buildSelectionTreeFromPaths(requestedFields)
      : buildSelectionTreeForValue(expectedData, field.type),
    preferredFieldOrder,
  );
  const selection = renderSelectionTree(selectionTree);
  const operationKeyword = rootTypeName === "Mutation" ? "mutation" : "query";

  return `${operationKeyword} ${variableDefinitions} { ${fieldName}${args}${selection ? ` ${selection}` : ""} }`;
}

function pickDeclaredVariables(
  schema: GraphQLSchema,
  operation: string,
  input: Record<string, unknown>,
): Record<string, unknown> {
  const { field } = getOperationField(schema, operation);
  return Object.fromEntries(
    field.args
      .filter((arg) => Object.hasOwn(input, arg.name))
      .map((arg) => [arg.name, input[arg.name]]),
  );
}

function getOperationOutputFieldOrder(
  document: BridgeDocument,
  operation: string,
): string[] {
  const [type, field] = operation.split(".") as [string, string];
  const bridge = document.instructions.find(
    (instruction): instruction is Bridge =>
      instruction.kind === "bridge" &&
      instruction.type === type &&
      instruction.field === field,
  );

  if (!bridge) {
    return [];
  }

  const seen = new Set<string>();
  const orderedFields: string[] = [];

  for (const wire of bridge.wires) {
    if (
      wire.to.module === SELF_MODULE &&
      wire.to.type === type &&
      wire.to.field === field &&
      wire.to.path.length > 0
    ) {
      const topLevel = wire.to.path[0]!;
      if (!seen.has(topLevel)) {
        seen.add(topLevel);
        orderedFields.push(topLevel);
      }
    }
  }

  return orderedFields;
}

function sortGraphQLErrorsByFieldOrder(
  errors: any[] | undefined,
  fieldOrder: string[],
): any[] | undefined {
  if (!errors || errors.length < 2 || fieldOrder.length === 0) {
    return errors;
  }

  const rank = new Map(
    fieldOrder.map((fieldName, index) => [fieldName, index]),
  );
  return [...errors].sort((left, right) => {
    const leftField = left?.path?.[1];
    const rightField = right?.path?.[1];
    const leftRank =
      typeof leftField === "string"
        ? (rank.get(leftField) ?? Number.MAX_SAFE_INTEGER)
        : Number.MAX_SAFE_INTEGER;
    const rightRank =
      typeof rightField === "string"
        ? (rank.get(rightField) ?? Number.MAX_SAFE_INTEGER)
        : Number.MAX_SAFE_INTEGER;
    return leftRank - rightRank;
  });
}

function shouldRelaxSelectedFieldErrors(
  errors: any[] | undefined,
  requestedFields?: string[],
): boolean {
  if (
    !errors ||
    errors.length === 0 ||
    !requestedFields ||
    requestedFields.length === 0
  ) {
    return false;
  }

  return errors.every((error) => {
    const path = Array.isArray(error?.path) ? error.path.slice(1) : [];
    if (
      path.length === 0 ||
      !path.every((segment: unknown) => typeof segment === "string")
    ) {
      return false;
    }

    const dotPath = path.join(".");
    return requestedFields.includes(dotPath);
  });
}

function setSelectedPathNull(
  target: Record<string, unknown>,
  path: string[],
): void {
  let cursor = target;

  for (const segment of path.slice(0, -1)) {
    const current = cursor[segment];
    if (!isPlainObject(current)) {
      cursor[segment] = {};
    }
    cursor = cursor[segment] as Record<string, unknown>;
  }

  const leaf = path[path.length - 1];
  if (leaf !== undefined && cursor[leaf] === undefined) {
    cursor[leaf] = null;
  }
}

function synthesizeSelectedGraphQLData(
  graphQLData: unknown,
  expectedData: unknown,
  requestedFields?: string[],
): unknown {
  if (!requestedFields || requestedFields.length === 0) {
    return graphQLData;
  }

  const base = isPlainObject(graphQLData)
    ? (cloneObservationValue(graphQLData) as Record<string, unknown>)
    : isPlainObject(expectedData)
      ? (cloneObservationValue(expectedData) as Record<string, unknown>)
      : {};

  for (const requestedField of requestedFields) {
    const path = requestedField.split(".").filter(Boolean);
    const selectedValue = getObservationPath(base, path);
    if (selectedValue === undefined) {
      setSelectedPathNull(base, path);
    }
  }

  return base;
}

// ── Types ───────────────────────────────────────────────────────────────────

/**
 * Context passed as the second argument to callback-form assert functions.
 * Lets assertions branch on engine or inspect wall-clock timing.
 */
export type AssertContext = {
  /** Which engine is running: "runtime" | "compiled". */
  engine: "runtime" | "compiled";
  /** High-resolution timestamp (ms) captured just before execution started. */
  startMs: number;
};

export type Scenario = {
  input: Record<string, any>;
  fields?: string[];
  tools?: Record<string, any>;
  timeout?: number;
  context?: Record<string, any>;
  /**
   * Allow the compiled engine to downgrade (fall back) to the runtime
   * interpreter for this scenario.
   *
   * - When **not set** (default): if the compiler downgrades, the test
   *   fails — the compiler should handle this bridge.
   * - When **set to `true`**: the test verifies that the downgrade
   *   actually happened (by checking for the warning log).
   */
  allowDowngrade?: boolean;
  assertData?: unknown | ((data: any, ctx: AssertContext) => void);
  assertError?: RegExp | ((error: any, ctx: AssertContext) => void);
  assertGraphql?:
    | Record<string, unknown>
    | ((data: any, errors: any[] | undefined) => void);
  assertLogs?: RegExp | ((logs: LogEntry[], ctx: AssertContext) => void);
  assertTraces: number | ((traces: ToolTrace[], ctx: AssertContext) => void);
  /**
   * Temporarily disable specific test aspects for this scenario.
   * The test is still defined (not removed) but will be skipped.
   */
  disable?: ("runtime" | "compiled" | "graphql")[];
};

export type RegressionTest = {
  bridge: string;
  tools?: Record<string, any>;
  context?: Record<string, any>;
  /** Tool-level timeout in ms (default: 5 000). */
  toolTimeoutMs?: number;
  scenarios: Record<string, Record<string, Scenario>>;
};

// ── Engine registry ─────────────────────────────────────────────────────────

const engines = [
  { name: "runtime", execute: executeRuntime },
  { name: "compiled", execute: executeCompiled },
] as const;

function assertDataExpectation(
  expectation: Scenario["assertData"],
  data: unknown,
  ctx?: AssertContext,
): void {
  if (expectation === undefined) {
    return;
  }

  if (typeof expectation === "function") {
    expectation(data, ctx!);
    return;
  }

  if (isPlainObject(expectation) && isPlainObject(data)) {
    for (const [key, expectedValue] of Object.entries(expectation)) {
      assertDataExpectation(expectedValue, data[key]);
    }
    return;
  }

  assert.deepStrictEqual(data, expectation);
}

function assertErrorExpectation(
  expectation: Scenario["assertError"],
  error: unknown,
  ctx?: AssertContext,
): void {
  if (expectation === undefined) {
    return;
  }

  if (typeof expectation === "function") {
    expectation(error, ctx!);
    return;
  }

  const message =
    typeof error === "object" &&
    error !== null &&
    "message" in error &&
    typeof (error as { message?: unknown }).message === "string"
      ? (error as { message: string }).message
      : String(error);
  const name =
    typeof error === "object" &&
    error !== null &&
    "name" in error &&
    typeof (error as { name?: unknown }).name === "string"
      ? (error as { name: string }).name
      : "";
  const errorText = `${name} ${message}`.trim();

  assert.match(errorText, expectation);
}

function assertLogsExpectation(
  expectation: Scenario["assertLogs"],
  logs: LogEntry[],
  ctx?: AssertContext,
): void {
  if (expectation === undefined) {
    return;
  }

  if (typeof expectation === "function") {
    expectation(logs, ctx!);
    return;
  }

  const logText = logs
    .map((entry) => `${entry.level}: ${entry.args.map(String).join(" ")}`)
    .join("\n");
  assert.match(logText, expectation);
}

function assertTraceExpectation(
  expectation: Scenario["assertTraces"],
  traces: ToolTrace[],
  ctx?: AssertContext,
): void {
  if (expectation === undefined) {
    return;
  }

  if (typeof expectation === "function") {
    expectation(traces, ctx!);
    return;
  }

  assert.equal(traces.length, expectation);
}

function hasGraphqlErrorRegexExpectation(
  expectation: Scenario["assertGraphql"],
): boolean {
  if (!expectation || typeof expectation === "function") {
    return false;
  }

  return collectGraphqlErrorRegexExpectations(expectation).length > 0;
}

function setGraphqlExpectedPath(
  target: Record<string, unknown>,
  path: string[],
  value: unknown,
): void {
  if (path.length === 0) {
    return;
  }

  let cursor: Record<string, unknown> = target;
  for (const segment of path.slice(0, -1)) {
    const next = cursor[segment];
    if (!isPlainObject(next)) {
      const replacement: Record<string, unknown> = {};
      cursor[segment] = replacement;
      cursor = replacement;
      continue;
    }
    cursor = next;
  }

  cursor[path[path.length - 1]!] = value;
}

function normalizeGraphqlExpectedValue(value: unknown): unknown {
  if (value instanceof RegExp) {
    return null;
  }

  if (Array.isArray(value)) {
    return value.map((entry) => normalizeGraphqlExpectedValue(entry));
  }

  if (isPlainObject(value)) {
    const normalized: Record<string, unknown> = {};
    for (const [key, nestedValue] of Object.entries(value)) {
      const path = key.split(".").filter(Boolean);
      setGraphqlExpectedPath(
        normalized,
        path,
        normalizeGraphqlExpectedValue(nestedValue),
      );
    }
    return normalized;
  }

  return value;
}

function normalizeGraphqlExpectedData(
  expectation: Record<string, unknown>,
): Record<string, unknown> {
  return normalizeGraphqlExpectedValue(expectation) as Record<string, unknown>;
}

function collectGraphqlErrorRegexExpectations(
  expectation: unknown,
  path: string[] = [],
): Array<{ path: string; pattern: RegExp }> {
  if (expectation instanceof RegExp) {
    return [{ path: path.join("."), pattern: expectation }];
  }

  if (Array.isArray(expectation)) {
    return expectation.flatMap((entry, index) =>
      collectGraphqlErrorRegexExpectations(entry, [...path, String(index)]),
    );
  }

  if (!isPlainObject(expectation)) {
    return [];
  }

  return Object.entries(expectation).flatMap(([key, value]) => {
    const keyPath = key.split(".").filter(Boolean);
    return collectGraphqlErrorRegexExpectations(value, [...path, ...keyPath]);
  });
}

export function assertGraphqlExpectation(
  expectation: Scenario["assertGraphql"],
  data: unknown,
  errors: any[] | undefined,
): void {
  if (expectation === undefined) {
    return;
  }

  if (typeof expectation === "function") {
    expectation(data, errors);
    return;
  }

  assert.deepStrictEqual(
    data,
    normalizeGraphqlExpectedData(expectation),
    "assertGraphql object expectations must deep-equal GraphQL data after replacing regex values with null",
  );

  for (const { path, pattern } of collectGraphqlErrorRegexExpectations(
    expectation,
  )) {
    const matchingError = (errors ?? []).find((error) => {
      const errorPath = Array.isArray(error?.path) ? error.path.slice(1) : [];
      return errorPath.map(String).join(".") === path;
    });

    assert.ok(matchingError, `Expected GraphQL error for field path "${path}"`);
    assert.match(String(matchingError?.message ?? matchingError), pattern);
  }
}

// ── Harness ─────────────────────────────────────────────────────────────────

export function regressionTest(name: string, data: RegressionTest) {
  describe(name, () => {
    const document: BridgeDocument = parseBridge(data.bridge);

    // Per-operation accumulated runtime trace bitmasks for coverage check
    const traceMasks = new Map<string, bigint>();

    test("parse → serialise → parse", () => {
      const serialised = serializeBridge(JSON.parse(JSON.stringify(document)));
      const parsed = parseBridge(serialised);

      assert.deepStrictEqual(
        normalizeDoc(document),
        normalizeDoc(parsed),
        "Document should be unchanged after serialise→parse round trip",
      );
    });

    for (const [operation, scenarios] of Object.entries(data.scenarios)) {
      describe(operation, () => {
        const scenarioNames = Object.keys(scenarios);
        const observedRuntimeSamples: Array<{
          scenarioName: string;
          output: unknown;
        }> = [];
        let pendingRuntimeTests = scenarioNames.filter(
          (name) => !scenarios[name]!.disable?.includes("runtime"),
        ).length;
        let resolveRuntimeCollection!: () => void;

        const runtimeCollectionDone = new Promise<void>((resolve) => {
          resolveRuntimeCollection = resolve;
          if (pendingRuntimeTests === 0) {
            resolve();
          }
        });

        afterEach((t) => {
          if (t.name !== "runtime") {
            return;
          }

          pendingRuntimeTests -= 1;
          if (pendingRuntimeTests === 0) {
            resolveRuntimeCollection();
          }
        });

        for (const [scenarioName, scenario] of Object.entries(scenarios)) {
          describe(scenarioName, () => {
            const tools = { ...data.tools, ...scenario.tools };
            const context = { ...data.context, ...scenario.context };

            for (const { name: engineName, execute } of engines) {
              test(engineName, async (t) => {
                if (scenario.disable?.includes(engineName)) {
                  t.skip("disabled");
                  return;
                }

                const { logs, logger } = createCapturingLogger();

                const timeout = new AbortController();

                // cancel when tests are aborted, or when scenario timeout is reached
                t.signal.onabort = () => timeout.abort();

                if (scenario.timeout !== undefined) {
                  if (scenario.timeout <= 0) {
                    timeout.abort();
                  } else {
                    setTimeout(() => timeout.abort(), scenario.timeout);
                  }
                }

                const executeOpts: ExecuteBridgeOptions = {
                  document,
                  operation,
                  input: scenario.input,
                  tools,
                  context,
                  signal: timeout.signal,
                  toolTimeoutMs: data.toolTimeoutMs ?? 5_000,
                  requestedFields: scenario.fields,
                  logger,
                  trace: "full" as const,
                };

                const startMs = performance.now();
                const assertCtx: AssertContext = { engine: engineName, startMs };

                try {
                  const {
                    data: resultData,
                    traces,
                    executionTraceId,
                  } = await execute(executeOpts);

                  if (engineName === "runtime") {
                    observedRuntimeSamples.push({
                      scenarioName,
                      output: resultData,
                    });
                  }

                  if (scenario.assertError) {
                    assert.fail("Expected an error but execution succeeded");
                  }

                  // Accumulate runtime trace coverage
                  if (engineName === "runtime") {
                    traceMasks.set(
                      operation,
                      (traceMasks.get(operation) ?? 0n) | executionTraceId,
                    );
                  }

                  assertDataExpectation(scenario.assertData, resultData, assertCtx);
                  assertTraceExpectation(scenario.assertTraces, traces, assertCtx);
                } catch (e: any) {
                  if (engineName === "runtime" && scenario.assertError) {
                    observedRuntimeSamples.push({
                      scenarioName,
                      output: undefined,
                    });
                  }

                  if (scenario.assertError) {
                    assertErrorExpectation(scenario.assertError, e, assertCtx);
                    assertTraceExpectation(
                      scenario.assertTraces,
                      e.traces ?? [],
                      assertCtx,
                    );
                    // Accumulate trace from errors too
                    if (
                      engineName === "runtime" &&
                      e.executionTraceId != null
                    ) {
                      traceMasks.set(
                        operation,
                        (traceMasks.get(operation) ?? 0n) |
                          BigInt(e.executionTraceId),
                      );
                    }
                  } else {
                    throw e;
                  }
                }

                // Compiler downgrade detection (compiled engine only)
                if (engineName === "compiled") {
                  const downgraded = logs.some(
                    (l) =>
                      l.level === "warn" &&
                      l.args.some(
                        (a) =>
                          typeof a === "string" &&
                          a.includes("Falling back to core executeBridge"),
                      ),
                  );
                  if (scenario.allowDowngrade) {
                    assert.ok(
                      downgraded,
                      "Expected compiler to downgrade to runtime but it " +
                        "compiled natively (remove allowDowngrade?)",
                    );
                    t.todo("this scenario needs to be supported in compiler");
                  } else if (downgraded) {
                    assert.fail(
                      "Compiler unexpectedly downgraded to runtime: " +
                        logs
                          .filter((l) => l.level === "warn")
                          .map((l) => l.args.join(" "))
                          .join("; "),
                    );
                  }
                }

                assertLogsExpectation(scenario.assertLogs, logs, assertCtx);
              });
            }
          });
        }

        const hasSuccessScenario = scenarioNames.some(
          (name) => !scenarios[name]!.assertError,
        );

        const allGraphqlDisabled = scenarioNames.every((name) =>
          scenarios[name]!.disable?.includes("graphql"),
        );

        if (scenarioNames.length > 0) {
          describe("graphql replay", () => {
            let rawSchema!: GraphQLSchema;
            let replayExemplar: Record<string, unknown> = {};

            before(async () => {
              await runtimeCollectionDone;

              if (allGraphqlDisabled) {
                // All scenarios have graphql disabled — no schema needed.
                return;
              }

              if (!hasSuccessScenario) {
                // Error-only operations have no output to infer a schema from.
                // Use a minimal JSONObject fallback so GraphQL replay still
                // exercises the error path through the full GraphQL stack.
                const [rootType, fieldName] = operation.split(".");
                const inputArgs = Object.keys(
                  scenarios[scenarioNames[0]!]!.input,
                );
                const argsDef = inputArgs.length
                  ? `(${inputArgs.map((a) => `${a}: JSONObject`).join(", ")})`
                  : "";
                const fallbackSDL = `scalar JSONObject\ntype ${rootType} {\n  ${fieldName}${argsDef}: JSONObject\n}\n`;
                rawSchema = buildGraphQLSchema(
                  ensureExecutableSDLForOperation(fallbackSDL, operation),
                );
                return;
              }

              const observer = new GraphQLSchemaObserver();

              replayExemplar = observedRuntimeSamples.reduce<
                Record<string, unknown>
              >((current, { scenarioName, output }) => {
                if (output === null || output === undefined) {
                  return current;
                }

                const scenario = scenarios[scenarioName]!;

                return {
                  ...current,
                  ...mergeObservedSelection(current, output, scenario.fields),
                };
              }, {});

              for (const { scenarioName, output } of observedRuntimeSamples) {
                const scenario = scenarios[scenarioName]!;
                observer.addInput(operation, scenario.input);

                if (output !== null && output !== undefined) {
                  observer.addOutput(
                    operation,
                    observationSampleForPlan(
                      replayExemplar,
                      output,
                      scenario.fields,
                    ),
                  );
                }
              }

              assert.ok(
                observedRuntimeSamples.some(
                  ({ output }) => output !== null && output !== undefined,
                ),
                `Cannot infer GraphQL schema for ${operation} without at least one successful scenario`,
              );

              const replaySDL = relaxInputNullabilityInSDL(
                ensureExecutableSDLForOperation(observer.toSDL(), operation),
              );

              rawSchema = buildGraphQLSchema(replaySDL);
            });

            for (const scenarioName of scenarioNames) {
              test(scenarioName, async (t) => {
                const scenario = scenarios[scenarioName]!;
                if (scenario.disable?.includes("graphql")) {
                  t.skip("disabled");
                  return;
                }

                const observedRuntimeData = observedRuntimeSamples.find(
                  (sample) => sample.scenarioName === scenarioName,
                )?.output;
                const replayExpectedData =
                  observedRuntimeData ?? replayExemplar;
                const tools = { ...data.tools, ...scenario.tools };
                const context: Record<string, unknown> = {
                  ...data.context,
                  ...scenario.context,
                };

                // Mirror the engine's AbortController setup so GraphQL replay
                // exercises the same abort path a real server would.
                // A real server always has a request signal; we replicate that here.
                const ac = new AbortController();
                t.signal.onabort = () => ac.abort();
                if (scenario.timeout !== undefined) {
                  if (scenario.timeout <= 0) {
                    ac.abort();
                  } else {
                    setTimeout(() => ac.abort(), scenario.timeout);
                  }
                }
                context.__bridgeSignal = ac.signal;

                const transformedSchema = bridgeTransform(rawSchema, document, {
                  tools,
                  signalMapper: (ctx) => ctx.__bridgeSignal,
                  toolTimeoutMs: data.toolTimeoutMs ?? 5_000,
                });
                const source = buildGraphQLOperationSource(
                  rawSchema,
                  operation,
                  replayExpectedData,
                  scenario.fields,
                  getOperationOutputFieldOrder(document, operation),
                );
                const result = await executeGraphQL({
                  schema: transformedSchema,
                  document: parseGraphQL(source),
                  variableValues: pickDeclaredVariables(
                    rawSchema,
                    operation,
                    scenario.input,
                  ),
                  contextValue: context,
                });

                // console.log(source, result);

                const [, fieldName] = operation.split(".");
                const normalizedGraphQLData = normalizeGraphQLValue(
                  (result.data as Record<string, unknown> | null)?.[fieldName],
                );
                const orderedGraphQLErrors = sortGraphQLErrorsByFieldOrder(
                  result.errors as any[] | undefined,
                  getOperationOutputFieldOrder(document, operation),
                );
                const relaxSelectedFieldErrors =
                  !hasGraphqlErrorRegexExpectation(scenario.assertGraphql) &&
                  shouldRelaxSelectedFieldErrors(
                    orderedGraphQLErrors,
                    scenario.fields,
                  );
                const graphQLErrors = relaxSelectedFieldErrors
                  ? undefined
                  : orderedGraphQLErrors;
                const graphQLData = relaxSelectedFieldErrors
                  ? synthesizeSelectedGraphQLData(
                      undefined,
                      replayExpectedData,
                      scenario.fields,
                    )
                  : normalizedGraphQLData;

                if (scenario.assertGraphql) {
                  assertGraphqlExpectation(
                    scenario.assertGraphql,
                    graphQLData,
                    graphQLErrors,
                  );
                  return;
                }

                if (scenario.assertError) {
                  assert.ok(
                    (graphQLErrors?.length ?? 0) > 0,
                    `GraphQL replay expected errors for ${operation}.${scenarioName}`,
                  );
                  return;
                }

                assert.deepStrictEqual(
                  graphQLErrors,
                  undefined,
                  `GraphQL execution failed for ${operation}.${scenarioName}: ${JSON.stringify(result.errors)}`,
                );

                assertDataExpectation(scenario.assertData, graphQLData);
              });
            }
          });
        }

        // After all scenarios for this operation, verify traversal coverage
        test("traversal coverage", (t) => {
          const allRuntimeDisabled = scenarioNames.every((name) =>
            scenarios[name]!.disable?.includes("runtime"),
          );
          if (allRuntimeDisabled) {
            t.skip("all scenarios have runtime disabled");
            return;
          }

          const [type, field] = operation.split(".") as [string, string];
          const bridge = document.instructions.find(
            (i): i is Bridge =>
              i.kind === "bridge" && i.type === type && i.field === field,
          );
          assert.ok(bridge, `Bridge ${operation} not found in document`);

          const manifest = buildTraversalManifest(bridge);
          const covered = traceMasks.get(operation) ?? 0n;

          const requiredBits = manifest.reduce(
            (mask, e) =>
              e.id.endsWith("/error")
                ? mask
                : mask | (1n << BigInt(e.bitIndex)),
            0n,
          );
          const missed = decodeExecutionTrace(
            manifest,
            requiredBits & ~covered,
          );

          if (missed.length > 0) {
            const lines = missed.map(
              (e) =>
                `  - ${e.id} (${e.kind}${e.description ? `: ${e.description}` : ""})`,
            );
            assert.fail(
              `${missed.length} traversal path(s) not covered by any scenario:\n${lines.join("\n")}`,
            );
          }
        });
      });
    }
  });
}
