type SourceLocation = import("@stackables/bridge-types").SourceLocation;

/**
 * Structured node reference — identifies a specific data point in the execution graph.
 *
 * Every wire has a "from" and "to", each described by a NodeRef.
 * The trunk (module + type + field + instance) identifies the node,
 * while path drills into its data.
 */
export type NodeRef = {
  /** Module identifier: "hereapi", "sendgrid", "zillow", or SELF_MODULE */
  module: string;
  /** GraphQL type ("Query" | "Mutation") or "Tools" for tool functions */
  type: string;
  /** Field or function name: "geocode", "search", "centsToUsd" */
  field: string;
  /** Instance number for tool calls (1, 2, ...) */
  instance?: number;
  /** References the current array element in a shadow tree (for per-element mapping) */
  element?: boolean;
  /** How many shadow-tree levels above the current element this ref targets. */
  elementDepth?: number;
  /** Path into the data: ["items", "0", "position", "lat"] */
  path: string[];
  /** True when the first `?.` is right after the root (e.g., `api?.data`) */
  rootSafe?: boolean;
  /** Per-segment safety flags (same length as `path`); true = `?.` before that segment */
  pathSafe?: boolean[];
};

/**
 * A single entry in a wire's fallback chain.
 *
 * Each entry is either a falsy gate (`||`) or a nullish gate (`??`).
 * The unified array allows mixing `||` and `??` in any order:
 *
 *   `o.x <- a.x || b.x ?? "default" || c.x`
 *
 * Exactly one of `ref`, `value`, or `control` should be set.
 */
export interface WireFallback {
  type: "falsy" | "nullish";
  ref?: NodeRef;
  value?: string;
  control?: ControlFlowInstruction;
  loc?: SourceLocation;
}

/**
 * A wire connects a data source (from) to a data sink (to).
 * Execution is pull-based: when "to" is demanded, "from" is resolved.
 *
 * Constant wires (`=`) set a fixed value on the target.
 * Pull wires (`<-`) resolve the source at runtime.
 * Pipe wires (`pipe: true`) are generated by the `<- h1:h2:source` shorthand
 * and route data through declared tool handles; the serializer collapses them
 * back to pipe notation.
 * Spread wires (`spread: true`) merge source object properties into the target.
 */
export type Wire =
  | {
      from: NodeRef;
      to: NodeRef;
      dispatchIndexRef?: NodeRef;
      loc?: SourceLocation;
      fromLoc?: SourceLocation;
      pipe?: true;
      /** When true, this wire merges source properties into target (from `...source` syntax). */
      spread?: true;
      safe?: true;
      fallbacks?: WireFallback[];
      catchLoc?: SourceLocation;
      catchFallback?: string;
      catchFallbackRef?: NodeRef;
      catchControl?: ControlFlowInstruction;
    }
  | {
      value: string;
      to: NodeRef;
      dispatchIndexRef?: NodeRef;
      loc?: SourceLocation;
    }
  | {
      cond: NodeRef;
      condLoc?: SourceLocation;
      thenRef?: NodeRef;
      thenValue?: string;
      thenLoc?: SourceLocation;
      elseRef?: NodeRef;
      elseValue?: string;
      elseLoc?: SourceLocation;
      to: NodeRef;
      dispatchIndexRef?: NodeRef;
      loc?: SourceLocation;
      fallbacks?: WireFallback[];
      catchLoc?: SourceLocation;
      catchFallback?: string;
      catchFallbackRef?: NodeRef;
      catchControl?: ControlFlowInstruction;
    }
  | {
      /** Short-circuit logical AND: evaluate left first, only evaluate right if left is truthy */
      condAnd: {
        leftRef: NodeRef;
        rightRef?: NodeRef;
        rightValue?: string;
        safe?: true;
        rightSafe?: true;
      };
      to: NodeRef;
      dispatchIndexRef?: NodeRef;
      loc?: SourceLocation;
      fallbacks?: WireFallback[];
      catchLoc?: SourceLocation;
      catchFallback?: string;
      catchFallbackRef?: NodeRef;
      catchControl?: ControlFlowInstruction;
    }
  | {
      /** Short-circuit logical OR: evaluate left first, only evaluate right if left is falsy */
      condOr: {
        leftRef: NodeRef;
        rightRef?: NodeRef;
        rightValue?: string;
        safe?: true;
        rightSafe?: true;
      };
      to: NodeRef;
      dispatchIndexRef?: NodeRef;
      loc?: SourceLocation;
      fallbacks?: WireFallback[];
      catchLoc?: SourceLocation;
      catchFallback?: string;
      catchFallbackRef?: NodeRef;
      catchControl?: ControlFlowInstruction;
    };

/**
 * Bridge definition — wires one GraphQL field to its data sources.
 */
export type Bridge = {
  kind: "bridge";
  /** GraphQL type: "Query" | "Mutation" */
  type: string;
  /** GraphQL field name */
  field: string;
  /** Declared data sources and their wire handles */
  handles: HandleBinding[];
  /** Connection wires */
  wires: Wire[];
  /**
   * When set, this bridge was declared with the passthrough shorthand:
   * `bridge Type.field with <name>`. The value is the define/tool name.
   */
  passthrough?: string;
  /** Handles to eagerly evaluate (e.g. side-effect tools).
   *  Critical by default — a forced handle that throws aborts the bridge.
   *  Add `catchError: true` (written as `force <handle> ?? null`) to
   *  swallow the error for fire-and-forget side-effects. */
  forces?: Array<{
    handle: string;
    module: string;
    type: string;
    field: string;
    instance?: number;
    /** When true, errors from this forced handle are silently caught (`?? null`). */
    catchError?: true;
  }>;
  arrayIterators?: Record<string, string>;
  pipeHandles?: Array<{
    key: string;
    handle: string;
    baseTrunk: {
      module: string;
      type: string;
      field: string;
      instance?: number;
    };
  }>;
};

/**
 * A handle binding — declares a named data source available in a bridge.
 *
 * Every wire reference in the bridge body must trace back to one of these.
 */
export type HandleBinding =
  | {
      handle: string;
      kind: "tool";
      name: string;
      version?: string;
      memoize?: true;
    }
  | { handle: string; kind: "input" }
  | { handle: string; kind: "output" }
  | { handle: string; kind: "context" }
  | { handle: string; kind: "const" }
  | { handle: string; kind: "define"; name: string };

/** Internal module identifier for the bridge's own trunk (input args + output fields) */
export const SELF_MODULE = "_";

/* c8 ignore start — pure TypeScript type declarations: no executable lines */

/**
 * Tool definition — a declared tool with wires, dependencies, and optional inheritance.
 *
 * Tool blocks define reusable, composable API call configurations:
 *   tool hereapi httpCall        — root tool with function name
 *   tool hereapi.geocode extends hereapi  — child inherits parent wires
 *
 * The engine resolves extends chains, merges wires, and calls the
 * registered tool function with the fully-built input object.
 */
export type ToolDef = {
  kind: "tool";
  /** Tool name: "hereapi", "sendgrid.send", "authService" */
  name: string;
  /** Function name — looked up in the tools map. Omitted when extends is used. */
  fn?: string;
  /** Parent tool name — inherits fn, deps, and wires */
  extends?: string;
  /** Dependencies declared via `with` inside the tool block */
  deps: ToolDep[];
  /** Wires: constants (`=`) and pulls (`<-`) defining the tool's input */
  wires: ToolWire[];
};

/**
 * A dependency declared inside a tool block.
 *
 *   with context                 — brings the full GraphQL context into scope
 *   with authService as auth     — brings another tool's output into scope
 */
export type ToolDep =
  | { kind: "context"; handle: string }
  | { kind: "tool"; handle: string; tool: string; version?: string }
  | { kind: "const"; handle: string };

/**
 * A wire in a tool block — either a constant value, a pull from a dependency,
 * or an error fallback.
 *
 * Examples:
 *   baseUrl = "https://example.com/"         → constant
 *   method = POST                                     → constant (unquoted)
 *   headers.Authorization <- ctx.sendgrid.token      → pull from context
 *   headers.Authorization <- auth.access_token       → pull from tool dep
 *   on error = { "lat": 0, "lon": 0 }               → constant fallback
 *   on error <- ctx.fallbacks.geo                     → pull fallback from context
 */
export type ToolWire =
  | { target: string; kind: "constant"; value: string }
  | { target: string; kind: "pull"; source: string }
  | { kind: "onError"; value: string }
  | { kind: "onError"; source: string };

/**
 * Context passed to every tool function as the second argument.
 *
 * Provides access to engine services (logger, etc.) without polluting the
 * input object.  Tools that don't need it simply ignore the second arg.
 */
// Re-exported from @stackables/bridge-types to break circular dependency
// with bridge-stdlib while maintaining backward-compatible imports.
export type {
  BatchToolCallFn,
  BatchToolFn,
  ToolContext,
  ScalarToolCallFn,
  ScalarToolFn,
  StreamToolCallFn,
  StreamToolFn,
  ToolCallFn,
  ToolMap,
  ToolMetadata,
  CacheStore,
  SourceLocation,
} from "@stackables/bridge-types";

/**
 * Explicit control flow instruction — used on the right side of fallback
 * gates (`||`, `??`, `catch`) to influence execution.
 *
 *   - `throw`    — raises a standard Error with the given message
 *   - `panic`    — raises a BridgePanicError that bypasses all error boundaries
 *   - `continue` — skips the current array element (sentinel value)
 *   - `break`    — halts array iteration (sentinel value)
 */
export type ControlFlowInstruction =
  | { kind: "throw"; message: string }
  | { kind: "panic"; message: string }
  | { kind: "continue"; levels?: number }
  | { kind: "break"; levels?: number };

/**
 * Named constant definition — a reusable value defined in the bridge file.
 *
 * Constants are available in bridge blocks via `with const as c` and in tool
 * blocks via `with const`. The engine collects all ConstDef instructions into
 * a single namespace object keyed by name.
 *
 * Examples:
 *   const fallbackGeo = { "lat": 0, "lon": 0 }
 *   const defaultCurrency = "EUR"
 */
export type ConstDef = {
  kind: "const";
  /** Constant name — used as the key in the const namespace */
  name: string;
  /** Raw JSON string — parsed at runtime when accessed */
  value: string;
};

/**
 * Version declaration — records the bridge file's declared language version.
 *
 * Emitted by the parser as the first instruction. Used at runtime to verify
 * that the standard library satisfies the bridge's minimum version requirement.
 *
 * Example:  `version 1.5`  →  `{ kind: "version", version: "1.5" }`
 */
export type VersionDecl = {
  kind: "version";
  /** Declared version string, e.g. "1.5" */
  version: string;
};

/** Union of all instruction types (excludes VersionDecl — version lives on BridgeDocument) */
export type Instruction = Bridge | ToolDef | ConstDef | DefineDef;

/**
 * Parsed bridge document — the structured output of the compiler.
 *
 * Wraps the instruction array with document-level metadata (version) and
 * provides a natural home for future pre-computed optimisations.
 */
export interface BridgeDocument {
  /** Declared language version (from `version X.Y` header). */
  version?: string;
  /** Original Bridge source text that produced this document. */
  source?: string;
  /** Optional logical filename associated with the source text. */
  filename?: string;
  /** All instructions: bridge, tool, const, and define blocks. */
  instructions: Instruction[];
}

/**
 * Define block — a reusable named subgraph (pipeline / macro).
 *
 * At parse time a define is stored as a template.  When a bridge declares
 * `with <define> as <handle>`, the define's handles and wires are inlined
 * into the bridge with namespaced identifiers for isolation.
 *
 * Example:
 *   define secureProfile {
 *     with userApi as api
 *     with input as i
 *     with output as o
 *     api.id <- i.userId
 *     o.name <- api.login
 *   }
 */
export type DefineDef = {
  kind: "define";
  /** Define name — referenced in bridge `with` declarations */
  name: string;
  /** Declared handles (tools, input, output, etc.) */
  handles: HandleBinding[];
  /** Connection wires (same format as Bridge wires) */
  wires: Wire[];
  /** Array iterators (same as Bridge) */
  arrayIterators?: Record<string, string>;
  /** Pipe fork registry (same as Bridge) */
  pipeHandles?: Bridge["pipeHandles"];
};
/* c8 ignore stop */
